apiVersion: apps/v1
kind: Deployment
metadata:
  name: servidor-archivos
spec:
  replicas: 3                    # <--- ¡AQUÍ ESTÁN TUS 3 RÉPLICAS! (25 Puntos)
  selector:
    matchLabels:
      app: servidor-seguro
  template:
    metadata:
      labels:
        app: servidor-seguro
    spec:
      containers:
      - name: contenedor-servidor
        image: servidor-seguro:v2  # Usamos tu imagen
        imagePullPolicy: Never     # IMPORTANTE: Usa la imagen local, no busques en internet
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: servicio-archivos
spec:
  type: LoadBalancer             # Esto nos permite entrar desde afuera
  selector:
    app: servidor-seguro
  ports:
    - protocol: TCP
      port: 5000                 # Puerto del Cluster
      targetPort: 5000           # Puerto del Contenedor